# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33cd280bd37738777ef501b1544541ed2d2e07d21df88af0f2acb1b4ac98b2d11d99ea2bf9b72d76085299f9d6091e564dc4894869571e685bce4525a1ac2369

test:
  secret_key_base: e4a7f3b3a49f448f9e995df9c777618eb4cf312c70a7335fe6920b16464c25a09e0c4aeaf0d5e98fb31cdd729a5501444d162ae610203d3ab63dc48f64bcacf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
